name: ${project.name}
main: com.poixson.backrooms.BackroomsPlugin
version: ${project.version}
api-version: ${spigot-short-version}
load: STARTUP
depend:
  - pxnPluginLib
  - Multiverse-Core
  - Vault
softdepend:
  - MoreFoods
  - dynmap
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
permissions:
    backrooms.*:
        default: op
        description: Gives access to all backrooms commands.
        children:
            backrooms.tp: true
            backrooms.tp.others: true
            backrooms.noclipfront: true
            backrooms.noclipback: true
            backrooms.level_111_button: true
    backrooms.tp:
        default: op
        description: Teleport to the backrooms
    backrooms.tp.others:
        default: op
        description: Teleport players to the backrooms
    backrooms.noclipfront:
        default: true
        description: Allow players to noclip from the frontrooms to the backrooms
    backrooms.noclipback:
        default: true
        description: Allow players to noclip inside the backrooms
    backrooms.level_111_button:
        default: true
        description: Allow players to teleport into level 111 run for your life.
