name: ${project.name}
main: com.poixson.backrooms.BackroomsPlugin
version: ${project.version}
api-version: ${spigot-short-version}
load: STARTUP
depend:
  - pxnCommonPluginMC
  - Multiverse-Core
softdepend:
  - dynmap
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
commands:
    backrooms:
        description: "Commands to administrate the backrooms"
        usage: "Usage: /backrooms <cmd>"
permission-message: "You don't have permission to use this command."
permissions:
    backrooms.*:
        default: op
        description: Gives access to all backrooms commands
        children:
            backrooms.reload: true
            backrooms.generate: true
            backrooms.clear: true
    backrooms.tp:
        default: op
        description: Teleport to the backrooms
    backrooms.tp.others:
        default: op
        description: Teleport players to the backrooms
